from .User import User
from .Role import Role
from .Patient import Patient
from .Service import Service
from .Appointment import Appointment
from .MedicalRecord import MedicalRecord
from .Consultation import Consultation
from .Payment import Payment
from .Reminder import Reminder